# Builds developing environment for rumors-api
#
version: '2'
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - "./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./volumes/nginx/sites-enabled:/etc/nginx/sites-enabled:ro"
      - "./volumes/nginx-logs:/var/log/nginx"
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.3.2
    ports:
      - "9200:9200"
    volumes:
      - "./volumes/esdata:/usr/share/elasticsearch/data"
    environment:
      - "path.repo=/usr/share/elasticsearch/data"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g" # Prevent elasticsearch eating up too much memory

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    # should contain MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD
    env_file: env-files/mongo
    volumes:
      - "./volumes/mongodata:/data/db"

  api:
    depends_on:
      - elasticsearch
      - mongo
    image: answerfamily/api
    ports:
      - "9000:9000"
    # See answerfamily-api's .env
    env_file: env-files/api
    environment:
      - NODE_ENV=production
